#!/bin/sh
[ $PASS = "**NULL**" ] && PASS=`601qaz106`
[ $PORT = "**NULL**" ] && PORT=`9621`
cat > /etc/shadowsocks/config.json << EOF
{
	"server":"0.0.0.0",
	"server_port":${PORT},
	"local_port":1080,
	"password":"${PASS}",
	"timeout":600,
	"method":"aes-256-cfb"
}
EOF
echo "=> The PORT is ${PORT}"
echo "=> The Password is ${PASS}"
ssserver -c /etc/shadowsocks/config.json
